steps:
- bash: echo hello world


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

# pool:
#   vmImage: ubuntu-latest

# variables:
#   buildConfiguration: 'Release'

# steps:
# -script: dotnet build