#pool: MyAgentPool
#steps:
#- bash: echo hello world
# trigger
# -main

# pool:
#   vmImage: ubuntu-latest

# variables:
#   buildConfiguration: 'Release'

# steps:
# -script: dotnet build

# pool: MyAgentPool
# task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: '**'
#     arguments: '--configuration Release' $(buildConfiguration)
# #   displayName: 'dotnet build $(buildConfiguration)'
